# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

states = State.create([
  {name: 'Alabama'},
  {name: 'Alaska'},
  {name: 'Arizona'},
  {name: 'Arkansas'},
  {name: 'California'},
  {name: 'Colorado'},
  {name: 'Connecticut'},
  {name: 'Delaware'},
  {name: 'District of Columbia'},
  {name: 'Florida'},
  {name: 'Georgia'},
  {name: 'Hawaii'},
  {name: 'Idaho'},
  {name: 'Illinois'},
  {name: 'Indiana'},
  {name: 'Iowa'},
  {name: 'Kansas'},
  {name: 'Kentucky'},
  {name: 'Louisiana'},
  {name: 'Maine'},
  {name: 'Maryland'},
  {name: 'Massachusetts'},
  {name: 'Michigan'},
  {name: 'Minnesota'},
  {name: 'Mississippi'},
  {name: 'Missouri'},
  {name: 'Montana'},
  {name: 'Nebraska'},
  {name: 'Nevada'},
  {name: 'New Hampshire'},
  {name: 'New Jersey'},
  {name: 'New Mexico'},
  {name: 'New York'},
  {name: 'North Carolina'},
  {name: 'North Dakota'},
  {name: 'Ohio'},
  {name: 'Oklahoma'},
  {name: 'Oregon'},
  {name: 'Pennsylvania'},
  {name: 'Rhode Island'},
  {name: 'South Carolina'},
  {name: 'South Dakota'},
  {name: 'Tennessee'},
  {name: 'Texas'},
  {name: 'Utah'},
  {name: 'Vermont'},
  {name: 'Virginia'},
  {name: 'Washington'},
  {name: 'West Virginia'},
  {name: 'Wisconsin'},
  {name: 'Wyoming'},
  {name: 'United States - Total'},
  ])

crimes = Crime.create([
  {name: 'violent_crime_rate'},
  {name: 'murder_and_nonnegligent_manslaughter_rate'},
  {name: 'forcible_rape_rate'},
  {name: 'robbery_rate'},
  {name: 'aggravated_assault_rate'},
  {name: 'property_crime_rate'},
  {name: 'burglary_rate'},
  {name: 'larceny_theft_rate'},
  {name: 'motor_vehicle_theft_rate'}
  ])

years = Year.create([
  {year: 1960},
  {year: 1961},
  {year: 1962},
  {year: 1963},
  {year: 1964},
  {year: 1965},
  {year: 1966},
  {year: 1967},
  {year: 1968},
  {year: 1969},
  {year: 1970},
  {year: 1971},
  {year: 1972},
  {year: 1973},
  {year: 1974},
  {year: 1975},
  {year: 1976},
  {year: 1977},
  {year: 1978},
  {year: 1979},
  {year: 1980},
  {year: 1981},
  {year: 1982},
  {year: 1983},
  {year: 1984},
  {year: 1985},
  {year: 1986},
  {year: 1987},
  {year: 1988},
  {year: 1989},
  {year: 1990},
  {year: 1991},
  {year: 1992},
  {year: 1993},
  {year: 1994},
  {year: 1995},
  {year: 1996},
  {year: 1997},
  {year: 1998},
  {year: 1999},
  {year: 2000},
  {year: 2001},
  {year: 2002},
  {year: 2003},
  {year: 2004},
  {year: 2005},
  {year: 2006},
  {year: 2007},
  {year: 2008},
  {year: 2009},
  {year: 2010},
  {year: 2011},
  {year: 2012},
  ])
  puts 'Seeded'
